---
# file: tasks/build/debug.yml
#
# build debug tasks.
#

- name: build | debug
  debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - httpd_build_dependencies
    - httpd_build_options
    - httpd_conf
    - httpd_configuration
    - httpd_configuration_envvars
    - httpd_default
    - httpd_dir
    - httpd_dir_cache
    - httpd_dir_configuration
    - httpd_dir_install
    - httpd_dir_lock
    - httpd_dir_lib
    - httpd_dir_run
    - httpd_dir_source
    - httpd_environment
    - httpd_download_url
    - httpd_download_url_asc
    - httpd_download_url_md5
    - httpd_force_build
    - httpd_installation
    - httpd_modules
    - httpd_modules_dynamic
    - httpd_modules_static
    - httpd_mpm_module
    - httpd_ports
    - httpd_service
    - httpd_sites
    - httpd_user.name
    - httpd_version
