---
# file: httpd/tasks/sites.yml
#
# site configuration tasks.
#

- name: sites | setup sites configuration
  template:
    src=etc/httpd/sites-available/site.conf.j2
    dest="{{ httpd_dir_configuration }}/sites-available/{{ item.order | default('000') }}-{{ item.name }}.conf"
    owner=root
    group=root
    mode=0644
  with_items: "{{ httpd_sites }}"
  when: "{{ item.enabled and item.configuration is defined }}"
  become: yes

- name: sites | enable sites
  file:
    src="{{ httpd_dir_configuration }}/sites-available/{{ item.order | default('000') }}-{{ item.name }}.conf"
    dest="{{ httpd_dir_configuration }}/sites-enabled/{{ item.order | default('000') }}-{{ item.name }}.conf"
    state=link
  with_items: "{{ httpd_sites }}"
  when: "{{ item.enabled }}"
  become: yes
  notify: restart httpd

- name: sites | disable sites
  file:
    path="{{ httpd_dir_configuration }}/sites-enabled/{{ item.order | default('000') }}-{{ item.name }}.conf"
    state=absent
  with_items: "{{ httpd_sites }}"
  when: "{{ not item.enabled }}"
  become: yes
  notify: restart httpd
