---
# file: httpd/tasks/package/main.yml
#
# package tasks file
#

- include: validation.yml
  tags: validation

- include: installation.yml
  tags: installation

- include: configuration.yml
  tags: configuration
