---
# file: httpd/tasks/package/validation.yml
#
# package validation tasks.
#

- name: package | validation | ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - httpd_conf
    - httpd_configuration
    - httpd_configuration_envvars
    - httpd_default
    - httpd_dir_configuration
    - httpd_dir_cache
    - httpd_dir_configuration
    - httpd_dir_lib
    - httpd_dir_lock
    - httpd_dir_log
    - httpd_dir_run
    - httpd_installation
    - httpd_modules_dynamic
    - httpd_service
    - httpd_sites
    - httpd_user
    - httpd_user.name
