---
# file: httpd/vars/build.yml
#
# build installation variables
#

httpd_build_dependencies:
  - libapr1-dev
  - libaprutil1-dev
  - libtool
  - pkg-config
  - expat
  - zlibc
  - build-essential
  - autoconf
  - automake
  - libtool
  - bison
  - pkg-config
  - re2c
  - libxml2-dev
  - libcurl4-openssl-dev
  - libbz2-dev
  - libjpeg-dev
  - libpng12-dev
  - libxpm-dev
  - libfreetype6-dev
  - libgmp3-dev
  - libmcrypt-dev
  - libmysqlclient-dev
  - libpspell-dev
  - librecode-dev
  - libssl-dev

httpd_dir: /usr/local/httpd
httpd_dir_cache: /var/cache/httpd
httpd_dir_configuration: /etc/httpd
httpd_dir_lock: /var/lock/httpd
httpd_dir_log: /var/log/httpd
httpd_dir_lib: /usr/lib/httpd
httpd_dir_run: /var/run/httpd
httpd_dir_source: /usr/local/src

httpd_force_build: no


httpd_modules_dynamic: []

httpd_modules_static:
  - name: authz_host
    enabled: yes
  - name: core
    enabled: yes
  - name: log_config
    enabled: yes
    configuration: |
      #
      # The following directives define some format nicknames for use with
      # a CustomLog directive.
      #
      # These deviate from the Common Log Format definitions in that they use %O
      # (the actual bytes sent including headers) instead of %b (the size of the
      # requested file), because the latter makes it impossible to detect partial
      # requests.
      #
      # Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
      # Use mod_remoteip instead.
      #
      LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
      LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
      LogFormat "%h %l %u %t \"%r\" %>s %O" common
      LogFormat "%{Referer}i -> %U" referer
      LogFormat "%{User-agent}i" agent
  - name: logio
    enabled: yes
  - name: authz_core
    enabled: yes
  - name: mpm_worker
    enabled: yes
    configuration: |
      ServerLimit         16
      StartServers         2
      MaxRequestWorkers  150
      MinSpareThreads     25
      MaxSpareThreads     75
      ThreadsPerChild     25
  - name: so
    enabled: yes
  - name: status
    enabled: yes
    configuration: |
      <Location /httpd-status>
          SetHandler server-status
          Require ip 127.0.0.1/32
      </Location>

      ExtendedStatus On

      <IfModule mod_proxy.c>
          ProxyStatus On
      </IfModule>
  - name: unixd
    enabled: yes
    configuration: |
      User ${APACHE_RUN_USER}
      Group ${APACHE_RUN_GROUP}

httpd_mpm_module: mpm_worker

httpd_ports:
  - 80

httpd_service: httpd

httpd_user:
  name: www-data
  home: /var/www-data
  shell: /usr/sbin/nologin


httpd_conf: []

httpd_configuration: |

  ServerRoot "{{ httpd_dir_configuration }}"

  # Include list of ports to listen on
  Include ports.conf

  # Include module configuration:
  IncludeOptional mods-enabled/*.load
  IncludeOptional mods-enabled/*.conf

  ServerSignature Off
  ServerTokens Prod

  # The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
  Mutex file:${APACHE_LOCK_DIR} default

  # The file in which the server should record its process identification number when it starts.
  PidFile ${APACHE_PID_FILE}

  # The number of seconds before receives and sends time out.
  Timeout 300

  # Whether or not to allow persistent connections (more than
  # one request per connection). Set to "Off" to deactivate.
  KeepAlive On

  # The maximum number of requests to allow during a persistent connection.
  # Set to 0 to allow an unlimited amount.
  MaxKeepAliveRequests 100

  # KeepAliveTimeout: Number of seconds to wait for the next request from the
  # same client on the same connection.
  KeepAliveTimeout 5

  # Log the names of clients or just their IP addresses.
  HostnameLookups Off

  # The location of the error log file.
  ErrorLog ${APACHE_LOG_DIR}/error.log

  # Control the severity of messages logged to the error_log.
  LogLevel warn


  # Sets the default security model of the Apache2 HTTPD server. It does
  # not allow access to the root filesystem outside of /usr/share and /var/www.
  # The former is used by web applications packaged in Debian,
  # the latter may be used for local directories served by the web server. If
  # your system is serving content from a sub-directory in /srv you must allow
  # access here, or in any related virtual host.
  <Directory />
      Options FollowSymLinks
      AllowOverride None
      Require all denied
  </Directory>

  <Directory /var/www/>
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
  </Directory>

  # Include generic snippets of statements
  IncludeOptional conf-enabled/*.conf

  # Include the virtual host configurations:
  IncludeOptional sites-enabled/*.conf

httpd_default: |
  ### htcacheclean settings ###

  ## run htcacheclean: yes, no, auto
  ## auto means run if /etc/httpd/mods-enabled/cache_disk.load exists
  ## default: auto
  HTCACHECLEAN_RUN=auto

  ## run mode: cron, daemon
  ## run in daemon mode or as daily cron job
  ## default: daemon
  HTCACHECLEAN_MODE=daemon

  ## cache size
  HTCACHECLEAN_SIZE=300M

  ## interval: if in daemon mode, clean cache every x minutes
  HTCACHECLEAN_DAEMON_INTERVAL=120

  ## path to cache
  ## must be the same as in CacheRoot directive
  HTCACHECLEAN_PATH={{ httpd_dir_cache }}/mod_cache_disk

  ## additional options:
  ## -n : be nice
  ## -t : remove empty directories
  HTCACHECLEAN_OPTIONS="-n"

httpd_dir_install: "{{ httpd_dir }}-{{ httpd_version }}"

httpd_environment: |
  unset HOME

  export APACHE_RUN_USER='{{ httpd_user.name }}'
  export APACHE_RUN_GROUP='{{ httpd_user.name }}'
  export APACHE_PID_FILE='{{ httpd_pid_file }}'
  export APACHE_RUN_DIR='{{ httpd_dir_run }}'
  export APACHE_LOCK_DIR='{{ httpd_dir_lock }}'
  export APACHE_LOG_DIR='{{ httpd_dir_log }}'

httpd_sites: []

httpd_tarball: "httpd-{{ httpd_version }}.tar.gz"


httpd_build_options:
  - "--with-mpm={{ httpd_mpm_module.replace('mpm_', '') }}"
  - "--prefix={{ httpd_dir_install }}"
  - "--enable-mods-static='{{ ' '.join(httpd_modules_static|map(attribute='name') | list | unique ) }}'"

httpd_download_url: "http://apache.osuosl.org//httpd/{{ httpd_tarball }}"
httpd_download_url_asc: "https://www.apache.org/dist/httpd/{{ httpd_tarball }}.asc"
httpd_download_url_md5: "https://www.apache.org/dist/httpd/{{ httpd_tarball }}.md5"

httpd_pid_file: "{{ httpd_dir_run }}/httpd.pid"
